### ISSUE TITLE
Wishlist: ua does not support HTTP compression

### ISSUE THREAD

**Issue by isync** [yusukebe/WebService-Simple#2]
I don't know if you regard this beyond the scope of this library, but supporting HTTP compression is probably helpful for many REST APIs, among them Amazon's.

Enabling this would involve using _decoded_content()_ instead of content() in modules implementing the parse_response() routine, and adding the compression header to requests, probably via _HTTP::Message::decodable()_ (look into Net::Amazon for inspiration).

Would be great,
thanks anyway!

**Comment by yusukebe** [comment]
Thank you for your issue. I try the implementation that this module supports HTTP compression on the next release.

**Comment by isync** [comment]
Done. :+1:
