### ISSUE TITLE
"No longer available"

### ISSUE THREAD

**Issue by eserte** [yusukebe/WebService-Simple#7]
Test suite fails:

```
...
request to http://gdata.youtube.com/feeds/api/videos?q=oasis failed at t/02_parser_xml_feed.t line 24.
# Looks like you planned 3 tests but ran 2.
# Looks like your test exited with 255 just after 2.
t/02_parser_xml_feed.t .... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/3 subtests 
..
```

In fact, http://gdata.youtube.com/feeds/api/videos?q=oasis just shows the string "No longer available"

**Comment by yusukebe** [comment]
YouTube API v2 has been depulicated. I'll write another example for testing. Thank you for your issue.

**Comment by yusukebe** [comment]
I made the test as using `search.cpan.org` uploads feed. YouTube feeds are not used now. Then, the tests will be pass!
